-- Chuyển sang cơ sở dữ liệu MASTER
USE MASTER;
GO

-- Kiểm tra và xóa cơ sở dữ liệu nếu tồn tại
IF EXISTS (SELECT * FROM SYS.DATABASES WHERE NAME = 'QLGH_NHOM5')
BEGIN
    ALTER DATABASE QLGH_NHOM5 SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE QLGH_NHOM5;
END
GO

-- Tạo cơ sở dữ liệu mới
CREATE DATABASE QLGH_NHOM5;
GO
USE QLGH_NHOM5;
GO

-- Tạo bảng KHACHHANG
CREATE TABLE KHACHHANG (
    MAKHACHHANG CHAR(10) PRIMARY KEY,
    TENCONGTY NVARCHAR(50),
    TENGIAODICH NVARCHAR(50),
    DIACHI NVARCHAR(100),
    EMAIL VARCHAR(50),
    SDT VARCHAR(11),
    FAX VARCHAR(10)
);

-- Tạo bảng DONDATHANG
CREATE TABLE DONDATHANG (
    SOHOADON CHAR(10) PRIMARY KEY,
    NGAYDATHANG DATE,
    NGAYGIAOHANG DATE,
    NGAYCHUYENHANG DATE,
    NOIGIAOHANG NVARCHAR(100),
    MAKHACHHANG CHAR(10),
	MANHANVIEN CHAR(7)
);

-- Tạo bảng NHANVIEN
CREATE TABLE NHANVIEN (
    MANHANVIEN CHAR(7) PRIMARY KEY,
    HO NVARCHAR(30),
    TEN NVARCHAR(30),
    NGAYSINH DATE,
    NGAYLAMVIEC DATE,
    DIACHI NVARCHAR(100),
    SDT VARCHAR(11),
    LUONGCOBAN MONEY,
    PHUCAP MONEY
);

-- Tạo bảng CHITIETDONDATHANG
CREATE TABLE CHITIETDONDATHANG (
    SOHOADON CHAR(10),
    MAHANG CHAR(5),
    GIABAN MONEY,
    SOLUONG INT,
    MUCGIAMGIA FLOAT,
    PRIMARY KEY (SOHOADON, MAHANG)
);

-- Tạo bảng MATHANG
CREATE TABLE MATHANG (
    MAHANG CHAR(5) PRIMARY KEY,
    TENHANG NVARCHAR(50),
    SOLUONG INT,
    DONVITINH NVARCHAR(20),
    GIAHANG MONEY,
    MALOAIHANG CHAR(5),
	MACONGTY CHAR(7)
);

-- Tạo bảng LOAIHANG
CREATE TABLE LOAIHANG (
    MALOAIHANG CHAR(5) PRIMARY KEY,
    TENLOAIHANG NVARCHAR(50)
);

-- Tạo bảng NHACUNGCAP
CREATE TABLE NHACUNGCAP (
    MACONGTY CHAR(7) PRIMARY KEY,
    TENCONGTY NVARCHAR(50),
    TENGIAODICH NVARCHAR(50),
    DIACHI NVARCHAR(100),
    SDT VARCHAR(11),
    FAX VARCHAR(10),
    EMAIL VARCHAR(50)
);

-- KHACHHANG và DONDATHANG
ALTER TABLE DONDATHANG
ADD CONSTRAINT FK_DONDATHANG_KHACHHANG
FOREIGN KEY (MAKHACHHANG) REFERENCES KHACHHANG(MAKHACHHANG);
---DONDATHANG và NHANVIEN
ALTER TABLE DONDATHANG
ADD CONSTRAINT FK_DONDATHANG_NHANVIEN
FOREIGN KEY (MANHANVIEN) REFERENCES NHANVIEN(MANHANVIEN);
-- DONDATHANG và CHITIETDONDATHANG
ALTER TABLE CHITIETDONDATHANG
ADD CONSTRAINT FK_CHITIETDONDATHANG_DONDATHANG
FOREIGN KEY (SOHOADON) REFERENCES DONDATHANG(SOHOADON);

-- CHITIETDONDATHANG và MATHANG
ALTER TABLE CHITIETDONDATHANG
ADD CONSTRAINT FK_CHITIETDONDATHANG_MATHANG
FOREIGN KEY (MAHANG) REFERENCES MATHANG(MAHANG);

-- MATHANG và LOAIHANG
ALTER TABLE MATHANG
ADD CONSTRAINT FK_MATHANG_LOAIHANG
FOREIGN KEY (MALOAIHANG) REFERENCES LOAIHANG(MALOAIHANG);

-- NHACUNGCAP và MATHANG
ALTER TABLE MATHANG
ADD CONSTRAINT FK_MATHANG_NHACUNGCAP
FOREIGN KEY (MACONGTY) REFERENCES NHACUNGCAP(MACONGTY);
